{{- $isSimpleScalable := eq (include "logstore.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstore.writeFullname" . }}
  namespace: {{ include "logstore.namespace" . }}
  labels:
    {{- include "logstore.writeLabels" . | nindent 4 }}
    {{- with .Values.logstore.serviceLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.write.service.labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  annotations:
    {{- with .Values.logstore.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.write.service.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.write.service.type }}
  ports:
    - name: http-metrics
      port: {{ .Values.logstore.server.http_listen_port }}
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: {{ .Values.logstore.server.grpc_listen_port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "logstore.writeSelectorLabels" . | nindent 4 }}
{{- end }}
