ARG BUILD_IMAGE=acme/logstore-build-image:0.34.0
ARG GO_VERSION=1.24
# Directories in this file are referenced from the root of the project not this folder
# This file is intended to be called from the root like so:
# docker build -t acme/promtail -f cmd/promtail/Dockerfile .
FROM golang:${GO_VERSION} AS goenv
RUN go env GOARCH > /goarch && \
  go env GOARM > /goarm

FROM $BUILD_IMAGE as build
COPY --from=goenv /goarch /goarm /
COPY . /src/logstore
WORKDIR /src/logstore
RUN make clean && GOARCH=$(cat /goarch) GOARM=$(cat /goarm) make BUILD_IN_CONTAINER=false logstore-canary

FROM gcr.io/distroless/static:debug
COPY --from=build /src/logstore/cmd/logstore-canary/logstore-canary /usr/bin/logstore-canary
SHELL [ "/busybox/sh", "-c" ]
RUN ln -s /busybox/sh /bin/sh
ENTRYPOINT [ "/usr/bin/logstore-canary" ]
