{{- with .Values.monitoring.logstoreCanary -}}
{{- if .enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstore-canary.fullname" $ }}
  labels:
    {{- include "logstore-canary.labels" $ | nindent 4 }}
  annotations:
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automountServiceAccountToken }}
{{- with $.Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
