{{- with .Values.monitoring.logstoreCanary -}}
{{- if .enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstore-canary.fullname" $ }}
  labels:
    {{- include "logstore-canary.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3500
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "logstore-canary.selectorLabels" $ | nindent 4 }}
{{- end -}}
{{- end -}}
