{{- $isDistributed := eq (include "logstore.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstore.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logstore.querierLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
  {{- with .Values.logstore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.querier.autoscaling.enabled }}
  replicas: {{ .Values.querier.replicas }}
{{- end }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.querier.maxSurge }}
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.logstore.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logstore.querierSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "logstore.config.checksum" . | nindent 8 }}
        {{- with .Values.logstore.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.querier.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "logstore.querierSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: memberlist
        {{- with .Values.logstore.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.querier.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      {{- with .Values.querier.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "logstore.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "logstore.querierPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.logstore.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.querier.terminationGracePeriodSeconds }}
      {{- with .Values.querier.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: querier
          image: {{ include "logstore.image" . }}
          imagePullPolicy: {{ .Values.logstore.image.pullPolicy }}
          args:
            - -config.file=/etc/logstore/config/config.yaml
            - -target=querier
            {{- if .Values.ingester.zoneAwareReplication.enabled }}
            {{- if and (.Values.ingester.zoneAwareReplication.migration.enabled) (not .Values.ingester.zoneAwareReplication.migration.readPath) }}
            - -distributor.zone-awareness-enabled=false
            {{- else }}
            - -distributor.zone-awareness-enabled=true
            {{- end }}
            {{- end }}
            {{- with .Values.querier.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          {{- with .Values.querier.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.querier.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.logstore.containerSecurityContext | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.logstore.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.logstore.livenessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/logstore/config
            - name: runtime-config
              mountPath: /etc/logstore/runtime-config
            - name: data
              mountPath: /var/logstore
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/logstore/license
            {{- end }}
            {{- with .Values.querier.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.querier.resources | nindent 12 }}
        {{- if .Values.querier.extraContainers }}
        {{- toYaml .Values.querier.extraContainers | nindent 8}}
        {{- end }}
      {{- with .Values.querier.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "logstore.configVolume" . | nindent 10 }}
        - name: runtime-config
          configMap:
            name: {{ template "logstore.name" . }}-runtime
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        - name: data
          emptyDir: {}
        {{- with .Values.querier.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
