{{- $isDistributed := eq (include "logstore.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed (gt (int .Values.querier.replicas) 1) }}
{{- if kindIs "invalid" .Values.querier.maxUnavailable }}
{{- fail "`.Values.querier.maxUnavailable` must be set when `.Values.querier.replicas` is greater than 1." }}
{{- else }}
apiVersion: {{ include "logstore.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "logstore.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logstore.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "logstore.querierSelectorLabels" . | nindent 6 }}
  {{- with .Values.querier.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
