ARG GO_VERSION=1.23
# Directories in this file are referenced from the root of the project not this folder
# This file is intended to be called from the root like so:
# docker build -t acme/logstore -f cmd/logstore/Dockerfile .
FROM golang:${GO_VERSION} as goenv
RUN go env GOARCH > /goarch && \
    go env GOARM > /goarm

COPY . /src/logstore
WORKDIR /src/logstore
RUN make clean && GOARCH=$(cat /goarch) GOARM=$(cat /goarm) make BUILD_IN_CONTAINER=false logstore

FROM gcr.io/distroless/base-nossl:debug

COPY --from=goenv /src/logstore/cmd/logstore/logstore /usr/bin/logstore
COPY cmd/logstore/logstore-local-config.yaml /etc/logstore/local-config.yaml

SHELL [ "/busybox/sh", "-c" ]

RUN addgroup -g 10001 -S logstore && \
    adduser -u 10001 -S logstore -G logstore
RUN mkdir -p /logstore && \
    chown -R logstore:logstore /etc/logstore /logstore && \
    ln -s /busybox/sh /bin/sh

USER 10001
EXPOSE 3100
ENTRYPOINT [ "/usr/bin/logstore" ]
CMD ["-config.file=/etc/logstore/local-config.yaml"]
