ARG BUILD_IMAGE=acme/logstore-build-image:0.24.1
# Directories in this file are referenced from the root of the project not this folder
# This file is intended to be called from the root like so:
# docker build -t acme/logstore -f cmd/logstore/Dockerfile .
FROM golang:1.19.2-alpine as goenv
RUN go env GOARCH > /goarch && \
    go env GOARM > /goarm

FROM --platform=linux/amd64 $BUILD_IMAGE as build
COPY --from=goenv /goarch /goarm /
COPY . /src/logstore
WORKDIR /src/logstore
RUN make clean && GOARCH=$(cat /goarch) GOARM=$(cat /goarm) make BUILD_IN_CONTAINER=false logstore

FROM alpine:3.16.2

RUN apk add --no-cache ca-certificates

COPY --from=build /src/logstore/cmd/logstore/logstore /usr/bin/logstore
COPY cmd/logstore/logstore-local-config.yaml /etc/logstore/local-config.yaml

RUN addgroup -g 10001 -S logstore && \
    adduser -u 10001 -S logstore -G logstore
RUN mkdir -p /logstore && \
    chown -R logstore:logstore /etc/logstore /logstore

# See https://example.com/acme/logstore/issues/1928
RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

USER 10001
EXPOSE 3100
ENTRYPOINT [ "/usr/bin/logstore" ]
CMD ["-config.file=/etc/logstore/local-config.yaml"]
