apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstore.name" . }}-runtime
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "logstore.labels" . | nindent 4 }}
data:
  runtime-config.yaml: |
    {{- tpl (toYaml .Values.logstore.runtimeConfig) . | nindent 4 }}
