{{- $isSimpleScalable := eq (include "logstore.deployment.isScalable" .) "true" -}}
{{- if and $isSimpleScalable (not .Values.read.legacyReadTarget ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstore.querySchedulerFullname" . }}-discovery
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "logstore.backendSelectorLabels" . | nindent 4 }}
    prometheus.io/service-monitor: "false"
  annotations:
    {{- with .Values.logstore.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.backend.service.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http-metrics
      port: {{ .Values.logstore.server.http_listen_port }}
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: {{ .Values.logstore.server.grpc_listen_port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "logstore.backendSelectorLabels" . | nindent 4 }}
{{- end }}
