ARG BUILD_IMAGE=acme/logstore-build-image:0.28.1
# Directories in this file are referenced from the root of the project not this folder
# This file is intended to be called from the root like so:
# docker build -t acme/promtail -f cmd/promtail/Dockerfile .
FROM golang:1.20.1-alpine as goenv
RUN go env GOARCH > /goarch && \
  go env GOARM > /goarm

FROM --platform=linux/amd64 $BUILD_IMAGE as build
COPY --from=goenv /goarch /goarm /
COPY . /src/logstore
WORKDIR /src/logstore
RUN make clean && GOARCH=$(cat /goarch) GOARM=$(cat /goarm) make BUILD_IN_CONTAINER=false logstore-querytee

FROM alpine:3.16.4
RUN apk add --update --no-cache ca-certificates
COPY --from=build /src/logstore/cmd/querytee/querytee /usr/bin/querytee
ENTRYPOINT [ "/usr/bin/querytee" ]
