{
 "title": "Logstore / Bloom Gateway",
 "tags": [ "logstore" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(logstore_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(logstore_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "logstore_datasource", "query": "logstore" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filter ratio - Bloom Gateway (server)",
   "type": "timeseries",
   "description": "Percentage of chunks that are filtered by using bloom filters",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(logstore_bloom_gateway_filtered_chunks_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_requested_chunks_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval]))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "sum(rate(logstore_bloom_gateway_filtered_series_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_requested_series_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval]))",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Filter ratio",
   "type": "gauge",
   "description": "Percentage of chunks that are filtered by using bloom filters",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstore_bloom_gateway_filtered_chunks_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__range]))\n/\nsum(increase(logstore_bloom_gateway_requested_chunks_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__range]))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "sum(increase(logstore_bloom_gateway_filtered_series_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__range]))\n/\nsum(increase(logstore_bloom_gateway_requested_series_sum{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__range]))",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"bloom-gateway\"}",
     "legendFormat": "Ready"
    },
    {
     "expr": "kube_statefulset_replicas{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"bloom-gateway\"}",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Filter ratio - Index Gateway (client)",
   "type": "timeseries",
   "description": "Percentage of chunks that are filtered by using bloom filters",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(logstore_bloom_gateway_querier_chunks_filtered_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_querier_chunks_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "sum(rate(logstore_bloom_gateway_querier_series_filtered_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_querier_series_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Filter ratio",
   "type": "gauge",
   "description": "Percentage of chunks that are filtered by using bloom filters",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstore_bloom_gateway_querier_chunks_filtered_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__range]))\n/\nsum(increase(logstore_bloom_gateway_querier_chunks_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__range]))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "sum(increase(logstore_bloom_gateway_querier_series_filtered_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__range]))\n/\nsum(increase(logstore_bloom_gateway_querier_series_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__range]))",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n    max by (pod, reason) (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"})\n    * on (pod) group_left\n    sum by (pod) (increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))\n) > 0",
     "legendFormat": "{{pod}} ({{reason}})"
    }
   ]
  },
  {
   "title": "Filter ratio - Index Gateway by route",
   "type": "timeseries",
   "description": "Percentage of chunks that are filtered by using bloom filters",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(logstore_index_gateway_prefilter_chunks_sum{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval])) by (route)\n    -\n    sum(rate(logstore_index_gateway_postfilter_chunks_sum{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval])) by (route)\n)\n/\nsum(rate(logstore_index_gateway_prefilter_chunks_sum{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval])) by (route)",
     "legendFormat": "chunks {{ route}}"
    }
   ]
  },
  {
   "title": "Data skipped because they don't match any bocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(logstore_bloom_gateway_querier_series_skipped_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_querier_series_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))",
     "legendFormat": "series"
    },
    {
     "expr": "sum(rate(logstore_bloom_gateway_querier_chunks_skipped_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))\n/\nsum(rate(logstore_bloom_gateway_querier_chunks_total{cluster=\"$cluster\", job=\"$namespace/index-gateway\"}[$__rate_interval]))",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Bloom Recorder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Found/Skipped/Missing chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_recorder_chunks_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=~\"(found|skipped|missed)\"}[$__rate_interval])) by (type)\n/ on () group_left\nsum(rate(logstore_bloom_recorder_chunks_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"requested\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filtered chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_recorder_chunks_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"filtered\"}[$__rate_interval])) by (type)\n/ on () group_left\nsum(rate(logstore_bloom_recorder_chunks_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"found\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Found/Skipped/Missing series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 454 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_recorder_series_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=~\"(found|skipped|missed)\"}[$__rate_interval])) by (type)\n/ on () group_left\nsum(rate(logstore_bloom_recorder_series_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"requested\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filtered series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 454 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_recorder_series_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"filtered\"}[$__rate_interval])) by (type)\n/ on () group_left\nsum(rate(logstore_bloom_recorder_series_total{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\", type=\"found\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 920 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"} |= \"level=error\" or \"panic:\" | logfmt"
      },
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"} |= \"level=warn\" | logfmt"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 920 },
     "targets": [
      {
       "expr": "sum by (level) (count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"} |~ \"level=(warn|error)\" | logfmt [$__auto]))"
      },
      {
       "expr": "sum (count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"} |= \"panic:\" | logfmt [$__auto]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1764 },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1764 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory (heap inuse)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2140 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2147 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(go_gc_cycles_total_gc_cycles_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2147 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(go_gc_duration_seconds_sum{container=\"bloom-gateway\"}[$__rate_interval]))\n/\nsum by (pod) (rate(go_gc_duration_seconds_count{container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC pauses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2147 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(go_gc_pauses_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(go_gc_pauses_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk reads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2154 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(instance, pod) (rate(node_disk_read_bytes_total[$__rate_interval]))\n+ ignoring(pod) group_right() \n(count by(instance, pod) (container_fs_reads_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-gateway\", device!~\".*sda.*\"}) * 0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2154 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(instance, pod) (rate(node_disk_written_bytes_total[$__rate_interval]))\n+ ignoring(pod) group_right() \n(count by(instance, pod) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-gateway\", device!~\".*sda.*\"}) * 0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk reads/writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2161 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_disk_read_bytes_total[$__rate_interval]))\n+ on(instance) group_right() \n(count by (instance) (container_fs_reads_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-gateway\", device!~\".*sda.*\"}) * 0))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(sum by(instance) (rate(node_disk_written_bytes_total[$__rate_interval]))\n+ on(instance) group_right() \n(count by(instance) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-gateway\", device!~\".*sda.*\"}) * 0)) * -1",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "QPS and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1175 },
     "targets": [
      {
       "expr": "sum by (status_code) (\n    rate(logstore_request_duration_seconds_count{cluster=\"$cluster\",job=\"$namespace/bloom-gateway\", route=\"/logproto.BloomGateway/FilterChunkRefs\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS per Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1175 },
     "targets": [
      {
       "expr": "sum by (pod) (\n    rate(logstore_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/bloom-gateway\", route=\"/logproto.BloomGateway/FilterChunkRefs\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1249 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le,route) (cluster_job_route:logstore_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}))",
       "legendFormat": "{{ route }} 50th percentile"
      },
      {
       "expr": "sum(cluster_job_route:logstore_request_duration_seconds_sum:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}) by (route)  / sum(cluster_job_route:logstore_request_duration_seconds_count:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}) by (route) ",
       "legendFormat": "{{ route }} Average"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:logstore_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}))",
       "legendFormat": "{{ route }} 99th percentile"
      },
      {
       "expr": "histogram_quantile(1, sum by (le,route) (cluster_job_route:logstore_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}))",
       "legendFormat": "{{ route }} max"
      }
     ]
    },
    {
     "title": "Per Pod Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1249 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n  sum(\n   rate(logstore_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"($namespace)/bloom-gateway\", route=~\"/logproto.BloomGateway/FilterChunkRefs\"}[$__rate_interval])\n   ) by (pod, le)\n )\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1176 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) (logstore_bloom_gateway_queue_length{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Queue Latency",
     "type": "timeseries",
     "description": "For how long do pending tasks stay in the queue",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1176 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(logstore_bloom_gateway_queue_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(logstore_bloom_gateway_queue_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum (logstore_bloom_gateway_queue_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"})\n/\nsum (logstore_bloom_gateway_queue_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Inflight tasks",
     "type": "timeseries",
     "description": "Inflight requests tracks all tasks both queued and in progress",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1176 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (quantile) (logstore_bloom_gateway_inflight_tasks{cluster=\"$cluster\", namespace=\"$namespace\", quantile=\"0.99\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time for tasks (per worker iteration)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1177 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(logstore_bloom_gateway_process_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(logstore_bloom_gateway_process_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(logstore_bloom_gateway_process_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p90"
      }
     ]
    },
    {
     "title": "Block query latency (single block)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1177 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(logstore_bloom_gateway_block_query_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(logstore_bloom_gateway_block_query_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(logstore_bloom_gateway_block_query_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{status}}-p90"
      }
     ]
    },
    {
     "title": "Tasks dequeued/processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1177 },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_gateway_tasks_dequeued_total{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "dequeued"
      },
      {
       "expr": "sum by (status) (rate(logstore_bloom_gateway_tasks_processed_total{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "processed {{status}}"
      }
     ]
    },
    {
     "title": "Worker Iterations per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1214 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_gateway_process_duration_seconds_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"bloom-gateway\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "We cache bloom blocks in memory to prevent the gateway from hitting the object store too often",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1178 }
    },
    {
     "title": "Cache size (per pod)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1179 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(logstore_bloom_blocks_cache_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(logstore_bloom_blocks_cache_entries{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"})",
       "legendFormat": "Items"
      },
      {
       "expr": "sum(rate(logstore_bloom_blocks_cache_added_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "Added"
      },
      {
       "expr": "sum(rate(logstore_bloom_blocks_cache_evicted_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval])) by (reason)",
       "legendFormat": "Evicted ({{reason}})"
      }
     ]
    },
    {
     "title": "Hit/Miss ratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1186 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (status) (\n    rate(logstore_bloom_blocks_cache_fetched_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval])\n)\n/ ignoring(status) group_left\nsum (\n    rate(logstore_bloom_blocks_cache_fetched_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average item size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1193 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(logstore_embeddedcache_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", cache=\"bloom-blocks-cache\", container=\"bloom-gateway\"})\n/\nsum(logstore_embeddedcache_entries{cluster=\"$cluster\", namespace=\"$namespace\", cache=\"bloom-blocks-cache\", container=\"bloom-gateway\"})",
       "legendFormat": "Size"
      },
      {
       "expr": "sum(logstore_bloom_blocks_cache_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"})\n/\nsum(logstore_bloom_blocks_cache_entries{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"})",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Bloom Store",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1193 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logstore_bloom_store_metas_fetched_sum{cluster=\"$cluster\",namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "metas fetch rate"
      },
      {
       "expr": "sum(rate(logstore_bloom_store_blocks_fetched_sum{cluster=\"$cluster\",namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "blocks fetch rate"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(logstore_bloom_store_blocks_fetched_size_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90 blocks size"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(logstore_bloom_store_metas_fetched_size_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90 metas size"
      }
     ]
    },
    {
     "title": "Block download queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1200 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job)(rate(logstore_bloom_store_download_queue_size_sum{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-gateway\"}[$__rate_interval]))",
       "legendFormat": "Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "The gateway download bloom meta files and blocks from the object store.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1013 }
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1014 }, "options": { "content": "---\n#### GCS\n" } },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 1014 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(logstore_gcs_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1014 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(logstore_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(logstore_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(logstore_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1021 }, "options": { "content": "---\n#### S3\n" } },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 1021 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(logstore_s3_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1021 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(logstore_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(logstore_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(logstore_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1028 },
     "options": {
      "content": "---\n#### Azure\nBlob Storage\n\n"
     }
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 1028 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(logstore_azure_blob_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1028 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(logstore_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(logstore_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(logstore_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dequeue duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1044 },
     "targets": [
      {
       "expr": "increase(logstore_bloom_gateway_dequeue_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dequeue count",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1044 },
     "targets": [
      {
       "expr": "increase(logstore_bloom_gateway_tasks_dequeued_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-gateway\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}