apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: true
    type: testdata
  - name: gdev-logstore
    type: logstore
    uid: gdev-logstore
    access: proxy
    url: http://host.docker.internal:3100
