apiVersion: v2
name: logstore
description: Helm chart for Acme Logstore in simple, scalable mode
type: application
appVersion: 2.8.0
version: 5.0.0
home: https://acme.github.io/helm-charts
sources:
  - https://example.com/acme/logstore
  - https://acme.com/oss/logstore/
  - https://acme.com/docs/logstore/latest/
icon: https://acme.com/docs/logstore/latest/logo_and_name.png
dependencies:
  - name: minio
    alias: minio
    version: 4.0.12
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: acme-agent-operator
    alias: acme-agent-operator
    version: 0.2.3
    repository: https://acme.github.io/helm-charts
    condition: monitoring.selfMonitoring.acmeAgent.installOperator
maintainers:
  - name: trevorwhitney
  - name: jeschkies
