{{- $isDistributed := eq (include "logstore.deployment.isDistributed" .) "true" -}}
{{- if (and $isDistributed (gt (int .Values.bloomPlanner.replicas) 0)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstore.bloomBuilderFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logstore.bloomBuilderLabels" . | nindent 4 }}
  {{- with .Values.logstore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.bloomBuilder.autoscaling.enabled }}
  replicas: {{ .Values.bloomBuilder.replicas }}
{{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.logstore.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logstore.bloomBuilderSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "logstore.config.checksum" . | nindent 8 }}
        {{- with .Values.logstore.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.bloomBuilder.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "logstore.bloomBuilderSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: memberlist
        {{- with .Values.logstore.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.bloomBuilder.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "logstore.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bloomBuilder.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "logstore.bloomBuilderPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.logstore.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.bloomBuilder.terminationGracePeriodSeconds }}
      containers:
        - name: bloom-builder
          image: {{ include "logstore.image" . }}
          imagePullPolicy: {{ .Values.logstore.image.pullPolicy }}
          {{- if or .Values.logstore.command .Values.bloomBuilder.command }}
          command:
            - {{ coalesce .Values.bloomBuilder.command .Values.logstore.command | quote }}
          {{- end }}
          args:
            - -config.file=/etc/logstore/config/config.yaml
            - -target=bloom-builder
            {{- with .Values.bloomBuilder.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          {{- with .Values.bloomBuilder.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bloomBuilder.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.logstore.containerSecurityContext | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.logstore.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/logstore/config
            - name: runtime-config
              mountPath: /etc/logstore/runtime-config
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/logstore/license
            {{- end }}
            - name: temp
              mountPath: /tmp
            - name: data
              mountPath: /var/logstore
            {{- with .Values.bloomBuilder.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.bloomBuilder.resources | nindent 12 }}
        {{- if .Values.bloomBuilder.extraContainers }}
        {{- toYaml .Values.bloomBuilder.extraContainers | nindent 8}}
        {{- end }}
      {{- with .Values.bloomBuilder.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bloomBuilder.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bloomBuilder.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "logstore.configVolume" . | nindent 10 }}
        - name: runtime-config
          configMap:
            name: {{ template "logstore.name" . }}-runtime
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        - name: temp
          emptyDir: {}
        - name: data
          emptyDir: {}
        {{- with .Values.bloomBuilder.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end -}}
