apiVersion: config.logstore.acme.com/v1
kind: ProjectConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: logstore-operator.acme.com
featureGates:
  #
  # Encryption feature gates
  #
  httpEncryption: true
  grpcEncryption: true
  #
  # Component feature gates
  #
  logstoreStackGateway: true
  restrictedPodSecurityStandard: false
  #
  # Webhook feature gates
  #
  logstoreStackWebhook: false
  alertingRuleWebhook: false
  recordingRuleWebhook: false
  rulerConfigWebhook: false
