{{- $isSimpleScalable := eq (include "logstore.deployment.isScalable" .) "true" -}}
{{- if and $isSimpleScalable (not .Values.read.legacyReadTarget ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstore.readFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: memberlist
    {{- include "logstore.readLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.logstore.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.read.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.read.autoscaling.enabled }}
  replicas: {{ .Values.read.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.logstore.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logstore.readSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/config.yaml") . | sha256sum }}
        {{- with .Values.logstore.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.read.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/part-of: memberlist
        {{- include "logstore.readSelectorLabels" . | nindent 8 }}
        {{- with .Values.logstore.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.read.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.read.selectorLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "logstore.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "logstore.readPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.logstore.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.read.terminationGracePeriodSeconds }}
      containers:
        - name: logstore
          image: {{ include "logstore.image" . }}
          imagePullPolicy: {{ .Values.logstore.image.pullPolicy }}
          args:
            - -config.file=/etc/logstore/config/config.yaml
            - -target={{ .Values.read.targetModule }}
            - -legacy-read-mode=false
            - -common.compactor-grpc-address={{ include "logstore.backendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:9095
            {{- with .Values.read.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          {{- with .Values.read.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.read.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.logstore.containerSecurityContext | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.logstore.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/logstore/config
            - name: runtime-config
              mountPath: /etc/logstore/runtime-config
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /var/logstore
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/logstore/license
            {{- end}}
            {{- with .Values.read.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.read.resources | nindent 12 }}
      {{- with .Values.read.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.read.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.read.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config
          {{- if .Values.logstore.existingSecretForConfig }}
          secret:
            secretName: {{ .Values.logstore.existingSecretForConfig }}
          {{- else }}
          {{- include "logstore.configVolume" . | nindent 10 }}
          {{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "logstore.name" . }}-runtime
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        {{- with .Values.read.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
