{{- $isSimpleScalable := eq (include "logstore.deployment.isScalable" .) "true" -}}
{{- if and $isSimpleScalable (gt (int .Values.read.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "logstore.readFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "logstore.readLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "logstore.readSelectorLabels" . | nindent 6 }}
  maxUnavailable: 1
{{- end }}
