{{- $isDistributed := eq (include "logstore.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstore.querySchedulerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logstore.querySchedulerLabels" . | nindent 4 }}
  {{- with .Values.logstore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.queryScheduler.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.logstore.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logstore.querySchedulerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "logstore.config.checksum" . | nindent 8 }}
        {{- with .Values.logstore.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.queryScheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "logstore.querySchedulerSelectorLabels" . | nindent 8 }}
        {{- with .Values.logstore.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.queryScheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: memberlist
    spec:
      serviceAccountName: {{ include "logstore.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryScheduler.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "logstore.querySchedulerPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.logstore.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.queryScheduler.terminationGracePeriodSeconds }}
      containers:
        - name: query-scheduler
          image: {{ include "logstore.image" . }}
          imagePullPolicy: {{ .Values.logstore.image.pullPolicy }}
          args:
            - -config.file=/etc/logstore/config/config.yaml
            - -target=query-scheduler
            {{- with .Values.queryScheduler.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          {{- with .Values.queryScheduler.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queryScheduler.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.logstore.containerSecurityContext | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.logstore.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.logstore.livenessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/logstore/config
            - name: runtime-config
              mountPath: /etc/logstore/runtime-config
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/logstore/license
            {{- end }}
            {{- with .Values.queryScheduler.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.queryScheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.queryScheduler.extraContainers }}
        {{- toYaml .Values.queryScheduler.extraContainers | nindent 8}}
        {{- end }}
      {{- with .Values.queryScheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryScheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryScheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "logstore.configVolume" . | nindent 10 }}
        - name: runtime-config
          configMap:
            name: {{ template "logstore.name" . }}-runtime
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        {{- with .Values.queryScheduler.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
